local_backend: true

backend:
  name: git-gateway
  #name: test-repo
  branch: cms-version

media_folder: "assets/img/blog"
public_folder: "/assets/img/blog"

collections:
  - name: "episodes"
    label: "Podcast-Folgen"
    label_singular: "Folge"
    description: "Alle Podcast-Episoden"
    format: "yaml"
    files:
      - file: "_data/podcasts.yml"
        label: "Folgen"
        name: "episodes"
        fields:
          - label: "Folgenliste"
            name: "episodes"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Kurzbeschreibung", name: "short", widget: "text" }
              - { label: "Langbeschreibung", name: "long", widget: "text" }
